---

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    daemon_reload: true

- name: Reload ufw
  ansible.builtin.command: ufw reload

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: reloaded
    daemon_reload: true

- name: Reload and restart apt timers
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl restart apt-daily-upgrade.timer
