---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start caddy.socket
  ansible.builtin.systemd:
    name: "{{ caddy_service_name }}.socket"
    enabled: yes
    state: started

- name: Enable and start caddy.service
  ansible.builtin.systemd:
    name: "{{ caddy_service_name }}.service"
    enabled: yes
    state: started


