---

- name: Allow HTTP traffic in UFW
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
  notify: reload ufw

- name: Allow HTTPS traffic in UFW
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
  notify: reload ufw

- name: Allow HTTP/3 traffic in UFW
  community.general.ufw:
    rule: allow
    port: 443
    proto: udp
  notify: reload ufw

- name: Install required packages
  ansible.builtin.apt:
    name:
      - libnginx-mod-http-brotli-filter
      - libnginx-mod-http-brotli-static
      - nginx
      - python3-certbot-nginx
      - python3-certbot
    state: present
    update_cache: yes
  notify: restart nginx

- name: Ensure nginx cache directory exists
  ansible.builtin.file:
    path: /var/cache/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Ensure nginx log directory exists
  ansible.builtin.file:
    path: /var/log/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Disable nginx default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Deploy global HTTP to HTTPS redirect
  ansible.builtin.copy:
    src: http_to_https_redirect.conf
    dest: /etc/nginx/sites-available/http_to_https_redirect
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Enable global HTTP redirect site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/http_to_https_redirect
    dest: /etc/nginx/sites-enabled/http_to_https_redirect
    state: link
  notify: restart nginx

- name: Enable and start nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started

- name: Ensure nginx scripts directory exists
  ansible.builtin.file:
    path: /srv/nginx
    state: directory
    owner: "{{ vault_podman_user }}"
    group: srvadmin
    mode: '0755'

- name: Copy Nginx scripts to srv directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/srv/nginx/{{ item | basename }}"
    owner: "{{ vault_podman_user }}"
    group: srvadmin
    mode: '0755'
  loop:
    - nginx-certbot-setup.sh
    - nginx-disable-site.sh
    - nginx-enable-site.sh

